name: ci
on:
  push:
  pull_request:
    branches:
      - main
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: cicd
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Test
        run: godot -s addons/gut/gut_cmdln.gd --path $PWD -gexit -gdir=res://test/unit
      - name: AlwaysRun
        if: always()
        run: echo This should always run
      - name: OnlyIfSuccess
        run: echo This should only run if there is no failure
      - name: OnlyIfFail
        if: failure()
        run: echo Tests Failed wooooooooo
          
