name: ci
on:
  push:
    branches:
      - main
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: cicd
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Test
        run: godot --no-window -s addons/gut/gut_cmdln.gd -d --path $PWD -gexit -gdir=res://test/unit
      - name: Shouldntfail
        run: echo Should not get here
          
