name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: cicd
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Unit Tests
        run: godot -s addons/gut/gut_cmdln.gd --path $PWD -gexit -gdir=res://test/unit -glog=2
      - name: Regression Tests
        run: godot -s addons/gut/gut_cmdln.gd --path $PWD -gexit -gdir=res://test/regression -glog=2
      - name: Integration Tests
        run: godot -s addons/gut/gut_cmdln.gd --path $PWD -gexit -gdir=res://test/integration -glog=2
